### ISSUE TITLE
openssl engine should fail when it's unable to resolve entropy from the server 

### ISSUE THREAD

**Issue by diega** [lacchain/openssl-pqe-engine#29]
Analyzing the latest logs from the integration tests, we discovered that if the ibrand_service is unable to successfully connect to the pqe-rpc-server, the `openssl rand 24` call returns some entropy, possibly coming from the _stdrand_engine_. In this case a failure is expected

Log output for reference: https://github.com/lacchain/openssl-pqe-engine/runs/1547188587?check_suite_focus=true#step:5:2945

**Comment by jg-cqc** [comment]
As a result of recent changes, this issue is now resolved.
If something happens causing the ibrand_service component to lose access to the remote ironbridge api, the following occurs:  
* Any requests to openssl for randomness are passed through to the ibrand_engine as per normal
* The ibrand_engine retrieves the requested amount of randomness from the "tank" (shared memory) and passes the data back to openssl, as normal.
* During this time, the ibrand_service is monitoring the water-level in the tank. Unaware of any potential network connection problems.
* If sufficient randomness is requested such that the water level in the tank falls below the low-water-mark, the service kicks in and sends a request to the api for more randomness. This service will wait for either a response or a timeout (on my system it was about two minutes.).
* During this time, the engine continues to service and fulfil requests from openssl, at least until the level in the tank is too low to fulfil the request, in which case it will wait for some seconds for the tank to be replenished, failing which returns an error back to openssl.
* OpenSSL then returns a non-zero return code (1) to the user, indicating a failure. No randomness is returned.
* If an OpenSSL request is then made to a specific alternate engine, e.g. ibinit (previously known as stdrand), then that engine can still supply randomness as requested.
* The service is periodically retrying the connection. If the connection is subsequently restored, then the service will proceed to fill the tank, and life goes on merrily.

I believe that this is the desired behaviour.

Test logs attached:
[TimeoutTest_console.log](https://github.com/lacchain/openssl-pqe-engine/files/5919316/TimeoutTest_console.log)
[TimeoutTest_syslog.log](https://github.com/lacchain/openssl-pqe-engine/files/5919317/TimeoutTest_syslog.log)

**Comment by diega** [comment]
thanks @jg-cqc!
